[project]
name = "geopackagemaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
dependencies = [
    "boto3>=1.37.7",
    "pandas>=2.2.3",
    "pygeopkg>=0.1.3",
]
